export default {
	// gruvred: '#cc241d',
	// gruvgreen: '#98971a',
	// gruvyellow: '#d79921',
	// gruvblue: '#458588',
	// gruvpurple: '#b16286',
	// gruvaqua: '#689d6a',
	// gruvorange: '#d65d0e',
	// gruvgray: '#928374',
	// gruvdgray: '#a89984',
	// gruvdbg: '#262626',
	// gruvdfg: '#ebdbb2',
	// gruvdemphred: '#fb4934',
	// gruvdemphgreen: '#b8bb26',
	// gruvdemphyellow: '#fabd2f',
	// gruvdemphblue: '#83a598',
	// gruvdemphpurple: '#d3869b',
	// gruvdemphaqua: '#8ec07c',
	// gruvdemphorange: '#fe8019',
	// gruvdbg0: '#262626',
	// gruvdbg0h: '#1d2021',
	// gruvdbg0s: '#32302f',
	// gruvdbg1: '#3c3836',
	// gruvdbg2: '#504945',
	// gruvdbg3: '#665c54',
	// gruvdbg4: '#7c6f64',
	// gruvdfg0: '#fbf1c7',
	// gruvdfg1: '#ebdbb2',
	// gruvdfg2: '#d5c4a1',
	// gruvdfg3: '#bdae93',
	// gruvdfg4: '#a89984',
	// gruvlbg: '#fbf1c7',
	// gruvlfg: '#3c3836',
	// gruvlgray: '#7c6f64',
	// gruvlemphred: '#9d0006',
	// gruvlemphgreen: '#79740e',
	// gruvlemphyellow: '#b57614',
	// gruvlemphblue: '#076678',
	// gruvlemphpurple: '#8f3f71',
	// gruvlemphaqua: '#427b58',
	// gruvlemphorange: '#af3a03',
	// gruvlbg0: '#fbf1c7',
	// gruvlbg0h: '#f9f5d7',
	// gruvlbg0s: '#f2e5bc',
	// gruvlbg1: '#ebdbb2',
	// gruvlbg2: '#d5c4a1',
	// gruvlbg3: '#bdae93',
	// gruvlbg4: '#a89984',
	// gruvlfg0: '#282828',
	// gruvlfg1: '#3c3836',
	// gruvlfg2: '#504945',
	// gruvlfg3: '#665c54',
	// gruvlfg4: '#7c6f64'
	gruvred: 'hsl(var(--gruvred))',
	gruvgreen: 'hsl(var(--gruvgreen))',
	gruvyellow: 'hsl(var(--gruvyellow))',
	gruvblue: 'hsl(var(--gruvblue))',
	gruvpurple: 'hsl(var(--gruvpurple))',
	gruvaqua: 'hsl(var(--gruvaqua))',
	gruvorange: 'hsl(var(--gruvorange))',
	gruvgray: 'hsl(var(--gruvgray))',
	gruvdgray: 'hsl(var(--gruvdgray))',
	gruvdbg: 'hsl(var(--gruvdbg))',
	gruvdfg: 'hsl(var(--gruvdfg))',
	gruvdemphred: 'hsl(var(--gruvdemphred))',
	gruvdemphgreen: 'hsl(var(--gruvdemphgreen))',
	gruvdemphyellow: 'hsl(var(--gruvdemphyellow))',
	gruvdemphblue: 'hsl(var(--gruvdemphblue))',
	gruvdemphpurple: 'hsl(var(--gruvdemphpurple))',
	gruvdemphaqua: 'hsl(var(--gruvdemphaqua))',
	gruvdemphorange: 'hsl(var(--gruvdemphorange))',
	gruvdbg0: 'hsl(var(--gruvdbg0))',
	gruvdbg0h: 'hsl(var(--gruvdbg0h))',
	gruvdbg0s: 'hsl(var(--gruvdbg0s))',
	gruvdbg1: 'hsl(var(--gruvdbg1))',
	gruvdbg2: 'hsl(var(--gruvdbg2))',
	gruvdbg3: 'hsl(var(--gruvdbg3))',
	gruvdbg4: 'hsl(var(--gruvdbg4))',
	gruvdfg0: 'hsl(var(--gruvdfg0))',
	gruvdfg1: 'hsl(var(--gruvdfg1))',
	gruvdfg2: 'hsl(var(--gruvdfg2))',
	gruvdfg3: 'hsl(var(--gruvdfg3))',
	gruvdfg4: 'hsl(var(--gruvdfg4))',
	gruvlbg: 'hsl(var(--gruvlbg))',
	gruvlfg: 'hsl(var(--gruvlfg))',
	gruvlgray: 'hsl(var(--gruvlgray))',
	gruvlemphred: 'hsl(var(--gruvlemphred))',
	gruvlemphgreen: 'hsl(var(--gruvlemphgreen))',
	gruvlemphyellow: 'hsl(var(--gruvlemphyellow))',
	gruvlemphblue: 'hsl(var(--gruvlemphblue))',
	gruvlemphpurple: 'hsl(var(--gruvlemphpurple))',
	gruvlemphaqua: 'hsl(var(--gruvlemphaqua))',
	gruvlemphorange: 'hsl(var(--gruvlemphorange))',
	gruvlbg0: 'hsl(var(--gruvlbg0))',
	gruvlbg0h: 'hsl(var(--gruvlbg0h))',
	gruvlbg0s: 'hsl(var(--gruvlbg0s))',
	gruvlbg1: 'hsl(var(--gruvlbg1))',
	gruvlbg2: 'hsl(var(--gruvlbg2))',
	gruvlbg3: 'hsl(var(--gruvlbg3))',
	gruvlbg4: 'hsl(var(--gruvlbg4))',
	gruvlfg0: 'hsl(var(--gruvlfg0))',
	gruvlfg1: 'hsl(var(--gruvlfg1))',
	gruvlfg2: 'hsl(var(--gruvlfg2))',
	gruvlfg3: 'hsl(var(--gruvlfg3))',
	gruvlfg4: 'hsl(var(--gruvlfg4))'
};
